
<template>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">New Note</div>
          <div class="card-body">
            <form action="#" method="post" @submit.prevent="store">
              <div class="form-group">
                <label for="title">Title</label>
                <input
                  type="text"
                  v-model="form.title"
                  id="title"
                  class="form-control"
                />
                <div v-if="theErrors.title" class="mt-2 text-danger"> *{{ theErrors.title[0] }}</div>
              </div>
              <div class="form-group">
                <label for="title">Subject</label>
                <div class="d-flex justify-content-between">
                  <select
                      v-model="form.subject"
                      id="subject"
                      class="form-control col-md-8"
                  >
                    <option v-for="subject in subjects" :key="subject.id" :value="subject.id">
                      {{subject.name}}
                    </option>

                  </select>
                  <create-subject></create-subject>
                </div>
                <div v-if="theErrors.subject" class="mt-2 text-danger"> *{{ theErrors.subject[0] }}</div>
              </div>
              <div class="form-group">
                <label for="title">Description</label>
                <textarea v-model="form.description" id="description" rows="5" class="form-control"></textarea>
                <div v-if="theErrors.description" class="mt-2 text-danger"> *{{ theErrors.description[0] }}</div>

              </div>
              <button type="submit" class="btn btn-primary d-flex align-items-center" >
                Save   
                <template v-if="loading == true">
                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(255, 255, 255,0); display: block; shape-rendering: auto;" width="20px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"> <g> <circle cx="60" cy="50" r="4" fill="#689cc5"> <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.67s"></animate> <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.67s"></animate> </circle> <circle cx="60" cy="50" r="4" fill="#689cc5"> <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.33s"></animate> <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.33s"></animate> </circle> <circle cx="60" cy="50" r="4" fill="#689cc5"> <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="0s"></animate> <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0s"></animate> </circle> </g><g transform="translate(-15 0)"> <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#93dbe9" transform="rotate(90 50 50)"></path> <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#93dbe9"> <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform> </path> <path d="M50 50L20 50A30 30 0 0 1 80 50Z" fill="#93dbe9"> <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;-45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform> </path> </g> <!-- [ldio] generated by https://loading.io/ --></svg>
                </template>
                </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import CreateSubject from "@/views/notes/CreateSubject";

export default {
  components: {CreateSubject},
  data() {
    return {
      form: {
          'title': '',
          'description': '',
          'subject': ''
      },
      loading: false,
      subjects: [],

      theErrors: [],
    };
  },

  mounted() {
    this.getSubjects();
  },

  methods: {
    async getSubjects() {
      let response = await axios.get("/api/subjects");

      if (response.status == 200) {
        this.subjects = response.data;
      }
    },
    async store() {
        try {
          this.loading = true
          let response = await axios.post("/api/notes/new-note", this.form);
          if (response.status == 200) {
              this.loading = false,
              this.form.title = "",
              this.form.subject = "",
              this.form.description = "",
              this.theErrors = [],
              this.$router.push('/notes')
              this.$swal.fire({
                  icon: 'success',
                  title: response.data.message,
                  showConfirmButton: false,
                  timer: 3000
                })
          }


        } catch (e) {
            this.$swal.fire({
              icon: 'error',
              title: 'Something went wrong',
              showConfirmButton: false,
              timer: 3000
            })

            this.theErrors = e.response.data.errors;
            this.loading = false
        }
    }
  },
};
</script>